export const sampleCategories = [
  { id: "cat1", name: "Web Development", slug: "web-development", description: "Learn modern web technologies like React, Node.js, and more" },
  { id: "cat2", name: "Data Science", slug: "data-science", description: "Master data analysis, visualization, and machine learning" },
  { id: "cat3", name: "Mobile Development", slug: "mobile-development", description: "Build iOS and Android apps with React Native and Flutter" },
  { id: "cat4", name: "DevOps", slug: "devops", description: "Learn deployment, CI/CD, and cloud infrastructure" },
  { id: "cat5", name: "UI/UX Design", slug: "ui-ux-design", description: "Create beautiful user interfaces and experiences" },
  { id: "cat6", name: "Cyber Security", slug: "cyber-security", description: "Protect systems and networks from digital attacks" },
]

export const sampleInstructors = [
  {
    id: "inst1",
    userId: "user_inst1",
    slug: "john-doe",
    firstName: "John",
    lastName: "Doe",
    bio: "Senior Full Stack Developer with 10+ years experience in React, Node.js, and cloud architectures.",
    expertise: ["React", "Node.js", "TypeScript", "AWS"],
    qualification: "MSc Computer Science",
    experienceYears: 10,
    rating: 4.8,
    profileImage: "/instructors/john.jpg",
    coursesCount: 5,
  },
  {
    id: "inst2",
    userId: "user_inst2",
    slug: "jane-smith",
    firstName: "Jane",
    lastName: "Smith",
    bio: "Data Scientist specialized in Machine Learning and Deep Learning with PhD from MIT.",
    expertise: ["Python", "TensorFlow", "Data Analysis", "Deep Learning"],
    qualification: "PhD Artificial Intelligence",
    experienceYears: 8,
    rating: 4.9,
    profileImage: "/instructors/jane.jpg",
    coursesCount: 3,
  },
  {
    id: "inst3",
    userId: "user_inst3",
    slug: "ahmad-hassan",
    firstName: "Ahmad",
    lastName: "Hassan",
    bio: "Mobile app developer with expertise in React Native and Flutter. Published 20+ apps on Play Store.",
    expertise: ["React Native", "Flutter", "Dart", "Firebase"],
    qualification: "BSc Software Engineering",
    experienceYears: 7,
    rating: 4.7,
    profileImage: "/instructors/ahmad.jpg",
    coursesCount: 4,
  },
  {
    id: "inst4",
    userId: "user_inst4",
    slug: "sarah-williams",
    firstName: "Sarah",
    lastName: "Williams",
    bio: "DevOps engineer at Google. Expert in Kubernetes, Docker, and cloud-native architectures.",
    expertise: ["Docker", "Kubernetes", "AWS", "Terraform"],
    qualification: "MSc Cloud Computing",
    experienceYears: 9,
    rating: 4.8,
    profileImage: "/instructors/sarah.jpg",
    coursesCount: 3,
  },
  {
    id: "inst5",
    userId: "user_inst5",
    slug: "mike-chen",
    firstName: "Mike",
    lastName: "Chen",
    bio: "UI/UX designer with 8+ years experience at top tech companies. Passionate about accessible design.",
    expertise: ["Figma", "Adobe XD", "CSS", "Design Systems"],
    qualification: "BSc Graphic Design",
    experienceYears: 8,
    rating: 4.6,
    profileImage: "/instructors/mike.jpg",
    coursesCount: 3,
  },
]

export const sampleCourses = [
  {
    id: "course1",
    title: "Complete Web Development Bootcamp",
    slug: "complete-web-development-bootcamp",
    shortDescription: "Learn HTML, CSS, JavaScript, React, Node.js from scratch to advanced level.",
    longDescription: "This comprehensive course covers everything you need to become a full-stack web developer. Starting from HTML fundamentals, you'll progress through CSS, JavaScript, React, Node.js, databases, and deployment. By the end, you'll have built multiple real-world projects and have the skills to apply for junior developer positions or freelance work.",
    price: 99.99,
    level: "ALL_LEVELS" as const,
    categoryId: "cat1",
    category: sampleCategories[0],
    isFeatured: true,
    isPublished: true,
    thumbnail: "/courses/web-dev.jpg",
    previewVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    whatYouWillLearn: [
      "Build responsive websites with HTML5 and CSS3",
      "Master JavaScript ES6+ features and modern patterns",
      "Create dynamic UIs with React and hooks",
      "Build REST APIs with Node.js and Express",
      "Work with MongoDB and PostgreSQL databases",
      "Deploy applications to production",
    ],
    requirements: ["Basic computer knowledge", "Willingness to learn"],
    prerequisites: ["No programming experience needed"],
    tags: ["html", "css", "javascript", "react", "nodejs", "fullstack"],
    durationHours: 120,
    accessExpiresInDays: 365,
    instructors: [sampleInstructors[0]],
    modules: [
      {
        id: "mod1",
        weekNumber: 1,
        title: "HTML & CSS Basics",
        slug: "html-css-basics",
        serial: 1,
        estimatedDuration: 120,
        contents: [
          { id: "cont1", title: "Introduction to HTML5", contentType: "VIDEO" as const, duration: 45, isLocked: false, serial: 1 },
          { id: "cont2", title: "CSS Flexbox & Grid Layout", contentType: "VIDEO" as const, duration: 60, isLocked: false, serial: 2 },
          { id: "cont3", title: "Responsive Design Principles", contentType: "TEXT" as const, duration: 30, isLocked: true, serial: 3 },
        ],
        quizzes: [
          { id: "quiz1", title: "HTML Basics Quiz", timeLimit: 15, passingScore: 70 },
        ],
      },
      {
        id: "mod2",
        weekNumber: 2,
        title: "JavaScript Fundamentals",
        slug: "javascript-fundamentals",
        serial: 2,
        estimatedDuration: 150,
        contents: [
          { id: "cont4", title: "Variables and Data Types", contentType: "VIDEO" as const, duration: 40, isLocked: true, serial: 1 },
          { id: "cont5", title: "ES6+ Features Deep Dive", contentType: "VIDEO" as const, duration: 90, isLocked: true, serial: 2 },
          { id: "cont6", title: "DOM Manipulation", contentType: "PDF" as const, duration: 30, isLocked: true, serial: 3 },
        ],
        quizzes: [
          { id: "quiz2", title: "JavaScript Quiz", timeLimit: 20, passingScore: 70 },
        ],
      },
      {
        id: "mod3",
        weekNumber: 3,
        title: "React for Beginners",
        slug: "react-beginners",
        serial: 3,
        estimatedDuration: 180,
        contents: [
          { id: "cont7", title: "React Components & JSX", contentType: "VIDEO" as const, duration: 60, isLocked: true, serial: 1 },
          { id: "cont8", title: "State and Props", contentType: "VIDEO" as const, duration: 75, isLocked: true, serial: 2 },
          { id: "cont9", title: "React Hooks In Depth", contentType: "VIDEO" as const, duration: 90, isLocked: true, serial: 3 },
          { id: "cont10", title: "Building a Todo App", contentType: "INTERACTIVE" as const, duration: 120, isLocked: true, serial: 4 },
        ],
        quizzes: [
          { id: "quiz3", title: "React Basics Quiz", timeLimit: 20, passingScore: 70 },
        ],
      },
      {
        id: "mod4",
        weekNumber: 4,
        title: "Node.js & Express",
        slug: "nodejs-express",
        serial: 4,
        estimatedDuration: 150,
        contents: [
          { id: "cont11", title: "Node.js Fundamentals", contentType: "VIDEO" as const, duration: 60, isLocked: true, serial: 1 },
          { id: "cont12", title: "Express.js REST APIs", contentType: "VIDEO" as const, duration: 90, isLocked: true, serial: 2 },
        ],
        quizzes: [],
      },
    ],
    enrollmentsCount: 1234,
    rating: 4.7,
  },
  {
    id: "course2",
    title: "Data Science with Python",
    slug: "data-science-with-python",
    shortDescription: "Master Python for data analysis, visualization, and machine learning.",
    longDescription: "Learn data manipulation with Pandas, numerical computing with NumPy, data visualization with Matplotlib and Seaborn, and build machine learning models with Scikit-learn. This course takes you from Python basics to building predictive models for real-world datasets.",
    price: 129.99,
    level: "INTERMEDIATE" as const,
    categoryId: "cat2",
    category: sampleCategories[1],
    isFeatured: true,
    isPublished: true,
    thumbnail: "/courses/data-science.jpg",
    previewVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    whatYouWillLearn: [
      "Data manipulation with Pandas and NumPy",
      "Data visualization with Matplotlib and Seaborn",
      "Statistical analysis and hypothesis testing",
      "Build ML models with Scikit-learn",
      "Feature engineering techniques",
      "Model evaluation and optimization",
    ],
    requirements: ["Basic Python knowledge", "High school math"],
    prerequisites: ["Python fundamentals"],
    tags: ["python", "data-science", "machine-learning", "pandas", "numpy"],
    durationHours: 150,
    accessExpiresInDays: 365,
    instructors: [sampleInstructors[1]],
    modules: [
      {
        id: "mod5",
        weekNumber: 1,
        title: "Python for Data Science",
        slug: "python-data-science",
        serial: 1,
        estimatedDuration: 120,
        contents: [
          { id: "cont13", title: "NumPy Arrays & Operations", contentType: "VIDEO" as const, duration: 60, isLocked: false, serial: 1 },
          { id: "cont14", title: "Pandas DataFrames", contentType: "VIDEO" as const, duration: 90, isLocked: false, serial: 2 },
        ],
        quizzes: [],
      },
      {
        id: "mod6",
        weekNumber: 2,
        title: "Data Visualization",
        slug: "data-visualization",
        serial: 2,
        estimatedDuration: 90,
        contents: [
          { id: "cont15", title: "Matplotlib Fundamentals", contentType: "VIDEO" as const, duration: 45, isLocked: true, serial: 1 },
          { id: "cont16", title: "Seaborn for Statistical Plots", contentType: "VIDEO" as const, duration: 45, isLocked: true, serial: 2 },
        ],
        quizzes: [],
      },
    ],
    enrollmentsCount: 856,
    rating: 4.8,
  },
  {
    id: "course3",
    title: "React Native Mobile Development",
    slug: "react-native-mobile-development",
    shortDescription: "Build cross-platform mobile apps for iOS and Android with React Native.",
    longDescription: "Master mobile app development with React Native. Learn to build beautiful, performant apps that work on both iOS and Android from a single codebase. Cover navigation, state management, API integration, and app store deployment.",
    price: 89.99,
    level: "INTERMEDIATE" as const,
    categoryId: "cat3",
    category: sampleCategories[2],
    isFeatured: true,
    isPublished: true,
    thumbnail: "/courses/react-native.jpg",
    previewVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    whatYouWillLearn: [
      "Build cross-platform mobile apps",
      "React Native components and navigation",
      "State management with Redux",
      "Native device features (camera, GPS)",
      "Publish to App Store and Play Store",
    ],
    requirements: ["React.js basics", "JavaScript knowledge"],
    prerequisites: ["Familiarity with React"],
    tags: ["react-native", "mobile", "ios", "android", "javascript"],
    durationHours: 100,
    accessExpiresInDays: 365,
    instructors: [sampleInstructors[2]],
    modules: [
      {
        id: "mod7",
        weekNumber: 1,
        title: "React Native Basics",
        slug: "react-native-basics",
        serial: 1,
        estimatedDuration: 90,
        contents: [
          { id: "cont17", title: "Setting Up Environment", contentType: "VIDEO" as const, duration: 30, isLocked: false, serial: 1 },
          { id: "cont18", title: "Core Components", contentType: "VIDEO" as const, duration: 60, isLocked: false, serial: 2 },
        ],
        quizzes: [],
      },
    ],
    enrollmentsCount: 623,
    rating: 4.7,
  },
  {
    id: "course4",
    title: "Docker & Kubernetes Masterclass",
    slug: "docker-kubernetes-masterclass",
    shortDescription: "Learn containerization and orchestration for modern DevOps practices.",
    longDescription: "From Docker basics to Kubernetes cluster management, this course covers everything you need to master containerization. Learn Docker Compose, Docker Swarm, Kubernetes deployments, services, and scaling.",
    price: 149.99,
    level: "ADVANCED" as const,
    categoryId: "cat4",
    category: sampleCategories[3],
    isFeatured: false,
    isPublished: true,
    thumbnail: "/courses/docker-k8s.jpg",
    previewVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    whatYouWillLearn: [
      "Docker fundamentals and best practices",
      "Write efficient Dockerfiles",
      "Docker Compose for multi-container apps",
      "Kubernetes architecture and concepts",
      "Deploy and scale apps on Kubernetes",
      "CI/CD pipelines with containers",
    ],
    requirements: ["Linux command line basics", "Basic networking knowledge"],
    prerequisites: ["Familiarity with cloud concepts"],
    tags: ["docker", "kubernetes", "devops", "containers", "orchestration"],
    durationHours: 80,
    accessExpiresInDays: 365,
    instructors: [sampleInstructors[3]],
    modules: [
      {
        id: "mod8",
        weekNumber: 1,
        title: "Docker Fundamentals",
        slug: "docker-fundamentals",
        serial: 1,
        estimatedDuration: 120,
        contents: [
          { id: "cont19", title: "What is Docker?", contentType: "VIDEO" as const, duration: 30, isLocked: false, serial: 1 },
          { id: "cont20", title: "Dockerfile Deep Dive", contentType: "VIDEO" as const, duration: 60, isLocked: true, serial: 2 },
          { id: "cont21", title: "Docker Compose", contentType: "VIDEO" as const, duration: 45, isLocked: true, serial: 3 },
        ],
        quizzes: [],
      },
    ],
    enrollmentsCount: 445,
    rating: 4.8,
  },
  {
    id: "course5",
    title: "UI/UX Design with Figma",
    slug: "ui-ux-design-figma",
    shortDescription: "Create stunning user interfaces and seamless user experiences with Figma.",
    longDescription: "Learn the complete UI/UX design process from research to high-fidelity prototypes. Master Figma tools, design systems, component libraries, and responsive design principles.",
    price: 79.99,
    level: "BEGINNER" as const,
    categoryId: "cat5",
    category: sampleCategories[4],
    isFeatured: true,
    isPublished: true,
    thumbnail: "/courses/ui-ux-figma.jpg",
    previewVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    whatYouWillLearn: [
      "UI/UX design principles",
      "Figma tools and workflows",
      "Component-based design systems",
      "Prototyping and user testing",
      "Responsive design techniques",
      "Design handoff to developers",
    ],
    requirements: ["Basic computer skills", "Creativity"],
    prerequisites: ["No design experience needed"],
    tags: ["figma", "ui", "ux", "design", "prototyping"],
    durationHours: 60,
    accessExpiresInDays: 365,
    instructors: [sampleInstructors[4]],
    modules: [
      {
        id: "mod9",
        weekNumber: 1,
        title: "Design Thinking",
        slug: "design-thinking",
        serial: 1,
        estimatedDuration: 60,
        contents: [
          { id: "cont22", title: "Introduction to UI/UX", contentType: "VIDEO" as const, duration: 30, isLocked: false, serial: 1 },
          { id: "cont23", title: "User Research Methods", contentType: "TEXT" as const, duration: 20, isLocked: false, serial: 2 },
        ],
        quizzes: [],
      },
    ],
    enrollmentsCount: 789,
    rating: 4.6,
  },
  {
    id: "course6",
    title: "Cyber Security Fundamentals",
    slug: "cyber-security-fundamentals",
    shortDescription: "Learn ethical hacking, network security, and threat detection techniques.",
    longDescription: "Comprehensive introduction to cybersecurity. Learn about common attack vectors, network security, encryption, penetration testing, and how to protect systems from threats.",
    price: 119.99,
    level: "BEGINNER" as const,
    categoryId: "cat6",
    category: sampleCategories[5],
    isFeatured: false,
    isPublished: true,
    thumbnail: "/courses/cyber-security.jpg",
    previewVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    whatYouWillLearn: [
      "Cybersecurity fundamentals and terminology",
      "Network security and防火墙",
      "Cryptography basics",
      "Ethical hacking techniques",
      "Threat detection and response",
      "Security best practices",
    ],
    requirements: ["Basic IT knowledge", "Networking basics"],
    prerequisites: ["Interest in security"],
    tags: ["cybersecurity", "ethical-hacking", "network-security", "encryption"],
    durationHours: 90,
    accessExpiresInDays: 365,
    instructors: [sampleInstructors[3]],
    modules: [
      {
        id: "mod10",
        weekNumber: 1,
        title: "Security Fundamentals",
        slug: "security-fundamentals",
        serial: 1,
        estimatedDuration: 90,
        contents: [
          { id: "cont24", title: "What is Cybersecurity?", contentType: "VIDEO" as const, duration: 30, isLocked: false, serial: 1 },
          { id: "cont25", title: "Common Threats & Attacks", contentType: "VIDEO" as const, duration: 45, isLocked: true, serial: 2 },
        ],
        quizzes: [],
      },
    ],
    enrollmentsCount: 534,
    rating: 4.7,
  },
]

export const sampleStudent = {
  id: "student1",
  userId: "user_student1",
  slug: "alamin",
  firstName: "Al Amin",
  lastName: "Hossain",
  profileImage: "/students/alamin.jpg",
  enrollments: [
    { courseId: "course1", course: sampleCourses[0], status: "ACTIVE" as const, enrolledAt: "2026-04-01" },
    { courseId: "course2", course: sampleCourses[1], status: "PENDING" as const, enrolledAt: "2026-04-15" },
  ],
  progress: [
    { courseId: "course1", progress: 65, completedContents: ["cont1", "cont2"] },
  ],
  certificates: [
    { id: "cert1", courseId: "course1", course: sampleCourses[0], issuedAt: "2026-03-15", certificateUrl: "/certs/cert1.pdf" },
  ],
}

export const sampleSessions = [
  {
    id: "sess1",
    title: "Live Q&A: Web Development Career Paths",
    instructor: sampleInstructors[0],
    type: "LIVE_CLASS" as const,
    semester: "ALL_LEVELS" as const,
    startTime: "2026-05-10T18:00:00",
    duration: 60,
    meetingUrl: "#",
  },
  {
    id: "sess2",
    title: "Support Session: Python Basics",
    instructor: sampleInstructors[1],
    type: "SUPPORT_SESSION" as const,
    semester: "FIRST" as const,
    startTime: "2026-05-12T14:00:00",
    duration: 45,
    meetingUrl: "#",
  },
]

export const sampleQuizzes = [
  {
    id: "quiz1",
    title: "HTML Basics Quiz",
    moduleId: "mod1",
    timeLimit: 30,
    passingScore: 70,
    questions: [
      {
        id: "q1",
        question: "What does HTML stand for?",
        options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language"],
        correctAnswer: 0,
      },
      {
        id: "q2",
        question: "Which tag is used for creating a hyperlink?",
        options: ["<link>", "<a>", "<href>"],
        correctAnswer: 1,
      },
    ],
  },
]

export const sampleBundles = [
  {
    id: "bundle1",
    title: "Full Stack Developer Bundle",
    slug: "full-stack-developer-bundle",
    description: "Master both frontend and backend development with this comprehensive bundle including Web Development, Data Science, and Mobile Development courses.",
    price: 199.99,
    isPublished: true,
    items: [
      { course: sampleCourses[0], priceAtBundleTime: 99.99 },
      { course: sampleCourses[1], priceAtBundleTime: 129.99 },
      { course: sampleCourses[2], priceAtBundleTime: 89.99 },
    ],
  },
  {
    id: "bundle2",
    title: "Data Science Mastery Bundle",
    slug: "data-science-mastery-bundle",
    description: "Become a data science expert with our curated collection of Python, ML, and analytics courses.",
    price: 249.99,
    isPublished: true,
    items: [
      { course: sampleCourses[1], priceAtBundleTime: 129.99 },
      { course: sampleCourses[5], priceAtBundleTime: 119.99 },
    ],
  },
  {
    id: "bundle3",
    title: "DevOps & Cloud Professional",
    slug: "devops-cloud-professional",
    description: "Learn containerization, orchestration, and cloud deployment to become a certified DevOps professional.",
    price: 219.99,
    isPublished: true,
    items: [
      { course: sampleCourses[3], priceAtBundleTime: 149.99 },
      { course: sampleCourses[5], priceAtBundleTime: 119.99 },
    ],
  },
]
