export enum tagTypes {
  Auth = "auth",
  Admin = "admin",
  Student = "student",
  Instructor = "instructor",
  Category = "category",
  Course = "course",
  Module = "module",
  Content = "content",
  CourseInstructor = "courseInstructor",
  Quiz = "quiz",
  QuizQuestion = "quizQuestion",
  QuizAttempt = "quizAttempt",
  Progress = "progress",
  Order = "order",
  Payment = "payment",
  Certificate = "certificate",
  Notice = "notice",
  Bundle = "bundle",
}

export const tagTypesList = [
  tagTypes.Auth,
  tagTypes.Admin,
  tagTypes.Student,
  tagTypes.Instructor,
  tagTypes.Category,
  tagTypes.Course,
  tagTypes.Module,
  tagTypes.Content,
  tagTypes.CourseInstructor,
  tagTypes.Quiz,
  tagTypes.QuizQuestion,
  tagTypes.QuizAttempt,
  tagTypes.Progress,
  tagTypes.Order,
  tagTypes.Payment,
  tagTypes.Certificate,
  tagTypes.Notice,
  tagTypes.Bundle,
];
